project:
  type: website
  output-dir: docs

website:
  title: "Kiwi Cervantes' ePortfolio"
  navbar:
    left:
      - href: index.html
        text: "Home"
      - href: about.html
        text: "About Me"
      - href: part_1.html
        text: "About the Data"
      - href: part_2.html
        text: "Cleaning and Visualizations"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source