project:
  type: website
  output-dir: docs

website:
  title: "Kiwi Cervantes' ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: kiwi-cervantes-portfolio/part_1.qmd
        text: "About the Data"
      - href: kiwi-cervantes-portfolio/part_2.qmd
        text: "Cleaning and Visualizations"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source