<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Are Video Games Brain Nourishment? – Kiwi Cervantes’ ePortfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Kiwi Cervantes’ ePortfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./part_1.html"> 
<span class="menu-text">About the Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./part_2.html"> 
<span class="menu-text">Cleaning and Visualizations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./410-project.html" aria-current="page"> 
<span class="menu-text">Linear Model Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">2. Methods</a>
  <ul class="collapse">
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection">2.1 Data Collection</a></li>
  <li><a href="#variable-creation" id="toc-variable-creation" class="nav-link" data-scroll-target="#variable-creation">2.2 Variable Creation</a></li>
  <li><a href="#analytic-methods" id="toc-analytic-methods" class="nav-link" data-scroll-target="#analytic-methods">2.3 Analytic Methods</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">3. Results</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">3.1 Exploratory Data Analysis</a></li>
  <li><a href="#automated-variable-selection" id="toc-automated-variable-selection" class="nav-link" data-scroll-target="#automated-variable-selection">3.2 Automated Variable Selection</a></li>
  <li><a href="#summary-results-of-model" id="toc-summary-results-of-model" class="nav-link" data-scroll-target="#summary-results-of-model">3.3 Summary Results of Model</a></li>
  </ul></li>
  <li><a href="#discussion-conclusion" id="toc-discussion-conclusion" class="nav-link" data-scroll-target="#discussion-conclusion">4. Discussion / Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">5. References</a></li>
  <li><a href="#statement-on-the-use-of-ai" id="toc-statement-on-the-use-of-ai" class="nav-link" data-scroll-target="#statement-on-the-use-of-ai">6. Statement on the Use of AI</a></li>
  <li><a href="#appendix-of-all-r-code" id="toc-appendix-of-all-r-code" class="nav-link" data-scroll-target="#appendix-of-all-r-code">7. Appendix of All R Code</a>
  <ul class="collapse">
  <li><a href="#library-packages-used" id="toc-library-packages-used" class="nav-link" data-scroll-target="#library-packages-used">7.1 Library Packages Used</a></li>
  <li><a href="#reading-in-data-data-cleaningvariable-creation" id="toc-reading-in-data-data-cleaningvariable-creation" class="nav-link" data-scroll-target="#reading-in-data-data-cleaningvariable-creation">7.2 Reading In Data &amp; Data Cleaning/Variable Creation</a></li>
  <li><a href="#exploratory-data-analysis-1" id="toc-exploratory-data-analysis-1" class="nav-link" data-scroll-target="#exploratory-data-analysis-1">7.3 Exploratory Data Analysis</a></li>
  <li><a href="#full-model-creation-output" id="toc-full-model-creation-output" class="nav-link" data-scroll-target="#full-model-creation-output">7.4 Full Model Creation &amp; Output</a></li>
  <li><a href="#variable-selection" id="toc-variable-selection" class="nav-link" data-scroll-target="#variable-selection">7.5 Variable Selection</a></li>
  <li><a href="#best-model-creation-nested-f-test-model-output" id="toc-best-model-creation-nested-f-test-model-output" class="nav-link" data-scroll-target="#best-model-creation-nested-f-test-model-output">7.6 Best Model Creation, Nested F-test &amp; Model Output</a></li>
  <li><a href="#assumptionscondition-checks-for-best-model" id="toc-assumptionscondition-checks-for-best-model" class="nav-link" data-scroll-target="#assumptionscondition-checks-for-best-model">7.7 Assumptions/Condition Checks for Best Model</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Are Video Games Brain Nourishment?</h1>
<p class="subtitle lead">An Exploration of the Impacts Video Games Have on Cognitive Functions</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="cervantes-k1-cornforth-c2-gutierrez-d3" class="level5">
<h5 class="anchored" data-anchor-id="cervantes-k1-cornforth-c2-gutierrez-d3">Cervantes, K<sup>1</sup>, Cornforth, C<sup>2</sup> , &amp; Gutierrez, D<sup>3</sup></h5>
<p><sup><em>1</em></sup><em>Department of Kinesiology, California State University Monterey Bay, Seaside, CA, USA</em><br>
<sup><em>2</em></sup><em>Department of Mathematics and Statistics, California State University Monterey Bay, Seaside, CA, USA</em> <sup><em>3</em></sup><em>Department of Applied Environmental Science, California State University Monterey Bay, Seaside, CA, USA</em></p>
</section>
<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>This study uses multiple linear regression to analyze data of local Monterey and CSUMB Super Smash Bros Ultimate (SSBU) Esports tournaments from individuals who voluntarily participated in a Psytool kit test to assess simple reaction. Cognitive speed is essential for excelling in various online games and high-intensity competitions. Within the Esports industry, competitive SSBU players must respond within thousandths of a second to capitalize on game-specific stimuli. Furthermore, medical studies support an improvement in cognitive abilities within the elderly who participate in real-time strategy video games. This study aimed to determine if gaming level and additional health/lifestyle characteristics would result in improved cognitive speed. Contrary to what was expected, our model revealed that only individuals categorized as elite gamers showed any significance for predicting simple reaction speed.</p>
</section>
<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<p>Many video games require quick reactions to play and win competitions, comparable to those in traditional sports (Bickman et al., 2021). Previous findings have found there to be a positive relationship between gaming habits and cognitive-motor ability. As such, regular gamers tend to outperform non-gamers when it comes to performing tasks in short-term memory and visual attentiveness (Boot et al., 2008). A recent study found evidence that asking participants about their gaming status positively affected performance for gamers and had an adverse effect on non-gamers in cognitive motor task performance (Ziv et. al., 2022). We hoped to apply these findings to the aging population and other groups that experience cognitive decline. Previous studies within the elderly population show that those who play real-time strategy video games saw an improvement in task switching, working memory, and visual short-term memory compared to those who did not (Basak et al., 2008). Understanding what factors may apply to improving cognitive performance is of great importance not only in the medical field but also in rehabilitation and development.</p>
<p>Esports, as a field, requires accuracy, where a thousandth of a second can determine whether a team or person wins. Skills such as quick reaction times increase the chances of success in faster-paced video games that require them (Ersin et al., 2022). Our model explored the relationship between simple reaction time and other predictive factors across different levels of competition. We expected to see our predictive variables of exercise hours a week, skill level, amount of sleep per night, age, and caffeine intake having an adverse relationship with reaction time. Other factors, such as dominant hand and sex, were investigated to see whether they had any predictive power. Evidence supports that faster reaction times have been found in right-hand-dominant people than left-hand-dominant people (Badau 2018).</p>
</section>
<section id="methods" class="level1">
<h1>2. Methods</h1>
<section id="data-collection" class="level2">
<h2 class="anchored" data-anchor-id="data-collection">2.1 Data Collection</h2>
<p>Data was collected from areas including local Monterey and CSUMB Esports tournaments, large scale Super Smash Bros Ultimate (SSBU) tournaments, and the CSU Monterey Bay library. Subjects voluntarily participated in a Psytool kit test to assess simple reaction time. The Psytool kit assessments were computerized tests administered in person. Participants were first administered a practice assessment to get them accustomed to the software and test. Succeeding was the actual assessment, where results were printed to a CSV file with the averages and peaks. Additionally, participants completed a questionnaire on weekly hours of sleep, caffeine intake, and other items of interest.</p>
</section>
<section id="variable-creation" class="level2">
<h2 class="anchored" data-anchor-id="variable-creation">2.2 Variable Creation</h2>
<p>Listed below are the variables relevant to the study categorized by their general purpose of measurement.</p>
<p>Health and Lifestyle:</p>
<ul>
<li>Sex - Male or Female</li>
<li>Age in years</li>
<li>Dominant hand</li>
<li>Caffeine Intake- Reported caffeine intake (mg) per day</li>
<li>Hours of sleep - Typical hours of sleep per night</li>
<li>Exercise hours per week</li>
</ul>
<p>Level of Gaming/Type:</p>
<ul>
<li>Gaming (measured as Non-Gamer, Casual-SB, Elite-SB)
<ul>
<li>Abbreviations: SB (Super Smash Bros Ultimate player)</li>
<li>Non-Gamer; play SSBU &lt;4 hours per week and exercise &lt;4 hours per week</li>
<li>Casual; play &gt;4 hours per week</li>
<li>Elite; top 150 globally-ranked competitive SSBU players as determined by 2024 Lumirank rankings</li>
</ul></li>
</ul>
<p>Cognitive measure test:</p>
<ul>
<li><p>Mean simple reaction practice test performance in milliseconds (ms)</p></li>
<li><p>Mean simple reaction practice test performance in milliseconds (ms)</p></li>
<li><p>Difference of means simple reaction test performance in milliseconds (ms); (Actual mean - Practice mean)</p></li>
</ul>
</section>
<section id="analytic-methods" class="level2">
<h2 class="anchored" data-anchor-id="analytic-methods">2.3 Analytic Methods</h2>
<p>Exploratory data analysis of the variables will be used to assess their potential significance for model creation. A boxplot will be used to illustrate differences in performance for the simple reaction test across the levels of gaming to assess any suggestive evidence for a difference that might indicate its importance for modelling the response. Other graphics and summary statistics to be included are a scatterplot, a QQ-plot, a residual plot, a Cook’s distance plot, and a VIF output for assessing model conditions (see Appendix).</p>
<p>Multiple linear regression will be used for the analysis of this study within RStudio. Provided that the response was a numerical value (simple reaction time mean), and all other explanatory variables were a mix of categorical and nominal, this model design was best suited. An automated best subset selection using Adjusted R-squared will be used for finding the best model form. A nested F-test will be performed to assess whether the suggested “best model” is significantly different from the original full model in which case the study would base all conclusions and assumption checks based on the output of the “best model”.</p>
</section>
</section>
<section id="results" class="level1">
<h1>3. Results</h1>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">3.1 Exploratory Data Analysis</h2>
<p>Our sample consists of 58 participants between the ages of 18 to 55, each grouped into levels gaming status: non-gamer (n = 18), casual (n = 21), and elite (n = 19) (Table 1 Appendix). In the boxplots (Figure 1), it’s shown that at least 75% of the mean actual simple reaction times (ms) of individuals categorized as Non-gamers (<span class="math inline">\(Q_{1} = 250.05\)</span>) reside above at least 75% of the reaction times for elite level (<span class="math inline">\(Q_{3} = 238.525\)</span>) and at least 50% of the data for casual gamers (<span class="math inline">\(M = 248.30\)</span>). Differences between the reported mean practice and mean actual simple reaction times prompted the use of the difference of these values as the response variable for model creation.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId27.png" style="width:6.5in;height:4.55in" class="figure-img"></p>
<figcaption>Figure 1. Distribution of mean actual reaction times (ms) among non-gamers, casual smash players, and competitive smash players</figcaption>
</figure>
</div>
<p>Figure 1. Distribution of mean actual reaction times (ms) among non-gamers, casual smash players, and competitive smash players</p>
</section>
<section id="automated-variable-selection" class="level2">
<h2 class="anchored" data-anchor-id="automated-variable-selection">3.2 Automated Variable Selection</h2>
<p>Results of the automated variable selection using best subsets with Adjusted <span class="math inline">\(R^{2}\)</span> found that the model should only include dominant hand, gaming level, simple reaction time practice mean (ms), and hours of sleep per night (hrs). The model produced an Adjusted <span class="math inline">\(R^{2}\)</span> = 0.2978, in comparison to the full model Adjusted <span class="math inline">\(R^{2}\)</span> = 0.2543 (see Variable Selection in Appendix). The nested F-test between the reduced (“best”) model and full model, showed no significant difference (F = 0.242, p = 0.9131, df = 4, <span class="math inline">\(\alpha\)</span> = 0.05) prompting the use of the reduced model for determining conclusions (see Nested F-test in Appendix ). All model conditions aside from linearity for the explanatory variables gaming level and dominant hand were met (see Assumption Check in Appendix). Below is the final model equation:</p>
<p><span class="math display">\[{\widehat{y}}_{srt\_ diff\_ mean} = 148.15475 - 3.56725x_{sleep\_ hours} - 11.23961x_{dominant\_ handR} - 11.19285x_{gamer\_ groupCasual} - 20.44156x_{gamer\_ groupElite} - 0.42982x_{srt\_ practice\_ mean}\]</span></p>
</section>
<section id="summary-results-of-model" class="level2">
<h2 class="anchored" data-anchor-id="summary-results-of-model">3.3 Summary Results of Model</h2>
<p>Overall the model was found to be a significant predictor (F(5, 52) = 5.834, p = 0.0002) of simple reaction time mean (ms), returning an Adjusted <span class="math inline">\(R^{2}\)</span> = 0.2978. The variables dominant hand, nightly hours of sleep, and the casual gamer group were each deemed to not be significant individual-level predictors of simple reaction time mean (all p-values &gt; 0.05). However, the elite gamer group (t = -2.822, p = 0.00674) and simple reaction time practice mean (ms) (t = -4.870, p = &lt;0.0001) were significant as shown below in Table 2.</p>
<section id="table-2-output-for-multiple-linear-regression-model" class="level6">
<h6 class="anchored" data-anchor-id="table-2-output-for-multiple-linear-regression-model">Table 2: Output for Multiple Linear Regression Model</h6>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">Estimate</th>
<th style="text-align: left;">SE</th>
<th style="text-align: left;">t</th>
<th style="text-align: left;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">148.15475</td>
<td style="text-align: left;">30.98086</td>
<td style="text-align: left;">4.782</td>
<td style="text-align: left;">1.47e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">sleep_hrs</td>
<td style="text-align: left;">-3.56725</td>
<td style="text-align: left;">2.46911</td>
<td style="text-align: left;">-1.445</td>
<td style="text-align: left;">0.15453</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dominant_handR</td>
<td style="text-align: left;">-11.23961</td>
<td style="text-align: left;">7.20737</td>
<td style="text-align: left;">-1.559</td>
<td style="text-align: left;">0.12495</td>
</tr>
<tr class="even">
<td style="text-align: left;">gamer_groupCasual</td>
<td style="text-align: left;">-11.19285</td>
<td style="text-align: left;">6.24879</td>
<td style="text-align: left;">-1.791</td>
<td style="text-align: left;">0.07908</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gamer_groupElite</td>
<td style="text-align: left;">-20.44156</td>
<td style="text-align: left;">7.24364</td>
<td style="text-align: left;">-2.822</td>
<td style="text-align: left;">0.00674</td>
</tr>
<tr class="even">
<td style="text-align: left;">srt_practice_mean</td>
<td style="text-align: left;">-0.42982</td>
<td style="text-align: left;">0.08825</td>
<td style="text-align: left;">-4.870</td>
<td style="text-align: left;">1.08e-05</td>
</tr>
</tbody>
</table>
<p>It is shown that participants from the elite gamer group are expected to have a simple reaction time practice mean 20.44 ms faster on average when compared to non-gamers, given dominant hand, simple reaction time practice mean (ms), and hours of sleep per night remain fixed. Additionally, for every 1 ms increase in simple reaction time practice mean, participants are expected to have a mean simple reaction time 0.43 ms faster on average, given dominant hand, nightly hours of sleep, and gaming level remain fixed (Table 2).</p>
</section>
</section>
</section>
<section id="discussion-conclusion" class="level1">
<h1>4. Discussion / Conclusion</h1>
<p>The purpose of this study is to determine whether an individual’s amount of exercise per week, gaming level, hours of sleep per night a week, age, practice mean performance for the simple reaction time, and caffeine intake predict the performance for the difference of means in a simple reaction test. In addition, sex and an individual’s dominant hand were considered in the model. Following automated best subset selection using Adjusted R^2, the only variables to be included were dominant hand, hours of sleep per night a week, gaming level, and the practice mean performance for the simple reaction time. Results of the nested F-test with the full and reduced model displayed no significant difference (F = 0.242, p-value = 0.9131). The best-suited model concluded that there is very strong evidence that at least one variable in the model has predictive power for the performance for the difference of means in a simple reaction test (F = 5.834, p-value = 0.000238). However, the model overall is a poor fit given the relatively low adjusted R^2 value (R^2 = 0.2978).</p>
<p>Our analyses showed that elite players tended to have faster reaction times than their casual and non-gamer counterparts (t=-2.822, p-value=.00674), but all other variables were not indicative of predicting reaction time within our model (all p-values &gt; 0.05). This aligns with the current literature that pro-athletes tend to have faster reaction times than their non-athlete equivalent (Atan &amp; Pelin, 2024). The results of variables such as age and hours of sleep (t=-1.445, p-value=0.15453) did not meet our hypotheses, as we expected to see a relationship in reaction time with older participants and in those who got less sleep. However, the variable age did not make it past variable selection; this may be due to age being an inclusion criterion in the study, and our sample comprising mostly college students. Being able to apply these results to people of older age was limited due to these factors. The dominant hand variable (t=-1.559, p=.12495), showing non-significance, may also be attributed to participants being used to using a controller with both hands, making the differences between the two hands negligible in comparison. These results may help us in bridging the connection between Esports athletes and traditional athletes and their physiological adaptations.</p>
<p>From our model, only 29.78% of the variability in simple reaction time can be explained by the linear model with the explanatory variables dominant hand, gaming level, simple reaction time practice mean (ms), and hours of sleep per night (hrs). This suggests that our variables are weak predictors of the response. More so, this indicates that more important factors exist for predicting simple reaction time.</p>
<p>Our initial exploratory data showed a constant failure in linearity between our variables. Possible plans would include the incorporation of interaction terms within the model. We were also limited by our sample size, both overall and within categories, creating a large amount of variance. Provided this was taken with a volunteer sample, our results are not generalizable to the larger population of Esports players, as well as limiting the clinical application of these results. Furthermore, the lack of randomization of the explanatory variables means no causal conclusions can be made between skill level and reaction time. Our results, that only the elite status is indicative of reaction time, should be further explored in studies looking into the relationship between Esports and cognitive performance, given these limitations.</p>
</section>
<section id="references" class="level1">
<h1>5. References</h1>
<p>Tülin, A., &amp; Akyol, P. (2014) “Reaction Times of Different Branch Athletes and Correlation between Reaction Time Parameters.” Procedia - Social and Behavioral Sciences, vol.&nbsp;116, Feb.&nbsp;2014, pp.&nbsp;2886–89. DOI.org (Crossref), https://doi.org/10.1016/j.sbspro.2014.01.674</p>
<p>Badau, D., Baydil, B., &amp; Badau, A. (2018). Differences among three measures of reaction time based on hand laterality in individual sports. Sports, 6(45).</p>
<p>Basak, C., Boot, W. R., Voss, M. W., &amp; Kramer, A. F. (2008). “Can Training in a Real-Time Strategy Video Game Attenuate Cognitive Decline in Older Adults?” Psychology and Aging, vol.&nbsp;23, no. 4, Dec.&nbsp;2008, pp.&nbsp;765–77. PubMed, https://doi.org/10.1037/a0013494</p>
<p>Bickman, P., Wechsler, K., Rudolf, K., Tholl, C., Frobose, I., &amp; Grieben, C. (2021). Comparison of reaction time between eSports players of different genres and sportsmen. International Journal of eSports Research, 1(1).</p>
<p>Boot, WR., Kramer, AF., Simons, DJ., Fabiani, M., Gratton, G. (2021) “The Effects of Video Game Playing on Attention, Memory, and Executive Control.” Acta Psychologica, vol.&nbsp;129, no. 3, Nov.&nbsp;2008, pp.&nbsp;387–98. ScienceDirect, https://doi.org/10.1016/j.actpsy.2008.09.005</p>
<p>Dell’Osso, L., Nardi, B., Massoni, L., Battaglini, S., De Felice, C., Bonelli, C., Pini, S., Cremone, I. M., &amp; Carpita, B. (2024). “Video Gaming in Older People: What Are the Implications for Cognitive Functions?” Brain Sciences, vol.&nbsp;14, no. 7, July 2024, p.&nbsp;731. PubMed Central, https://doi.org/10.3390/brainsci14070731</p>
<p>Ersin, A., Tezeren, H., Pekyavas, N., Asal, B., Atabey, A., Diri, A., &amp; Gonen, I. (2022). The relationship between reaction time and gaming time in E-sports players. Kinesiology, 54(1), 36-42.</p>
<p>Google. (2026). Gemini [Large language model]. google.com.</p>
<p>Ziv, G., Lidor, R. &amp; Levin, O. Reaction time and working memory in gamers and non-gamers. Sci Rep 12, 6798 (2022). https://doi.org/10.1038/s41598-022-10986-3</p>
</section>
<section id="statement-on-the-use-of-ai" class="level1">
<h1>6. Statement on the Use of AI</h1>
<pre><code>We used generative AI for troubleshooting code issues and discovering functions. An example of a prompt that we used was “How to turn a character variable into a factor variable in R” and similar prompts. Additional prompts included “why is the LOOCV returning NaN?” when we explored the idea of cross-validation. The AI source used was the generic google search AI overview (Gemini). All source searching, interpretations, and discussions were done by the authors of the paper.</code></pre>
</section>
<section id="appendix-of-all-r-code" class="level1">
<h1>7. Appendix of All R Code</h1>
<section id="library-packages-used" class="level2">
<h2 class="anchored" data-anchor-id="library-packages-used">7.1 Library Packages Used</h2>
<pre><code>#mosaic package makes some functions more user-friendly for Intro Stat topics
library(mosaic)
#ggformula &amp; ggplot2 packages are for graphics
library(ggformula)
library(ggplot2)
#janitor package will help us clean up variable names
library(janitor)
#dplyr, tidyverse, and forcats packages will help with data cleaning (managing tidy data)
library(dplyr)
library(tidyverse)
library(forcats)
#for nicely formatted tables of parameter estimates and related statistics.
library(gtsummary)
# color package
library(paletteer)
# for nicely formatted tables of parameter estimates and related statistics
library(gt)
# For automated variable selection
library(leaps)
# for Nested F-test
library(car)</code></pre>
</section>
<section id="reading-in-data-data-cleaningvariable-creation" class="level2">
<h2 class="anchored" data-anchor-id="reading-in-data-data-cleaningvariable-creation">7.2 Reading In Data &amp; Data Cleaning/Variable Creation</h2>
<pre><code>#Read and cleaning data: Ensuring numerical values are treated as such.
esports_raw &lt;- read_csv("esports_joined_fixed.csv",
                        col_types = list('simple_reaction_time_mean_rt' = col_double(),
                                         'simple_reaction_time_actual_mean_rt_ms' = col_double(),
                                         'simple_reaction_time_practice_mean_rt_ms' = col_double(),
                                         'non_gamers_exercise_hours_week' = col_double(),
                                         'non_gamers_gaming_hr_week' = col_double(),
                                         'non_gamers_caffeine_intake_mg_d' = col_double(),
                                         'non_gamers_age_y' = col_double(),
                                         'non_gamers_sleep_hours_night' = col_double()))

# Cleaning data: Reassigning the values for gamer level and re-leveling the categories
non_cas_elite &lt;- esports_raw|&gt;
  filter(str_detect(participant_code, "NG") |
           str_detect(participant_code, "CAS") |
           str_detect(participant_code, "ES"))|&gt;
  mutate(gamer_group = case_when(
    str_starts(participant_code, "NG") ~ "Non-Gamer",
    str_starts(participant_code, "CAS") ~ "Casual",
    str_starts(participant_code, "ES") ~ "Elite"
  ))|&gt; 
  mutate(gamer_group = factor(gamer_group, 
                          levels = c("Non-Gamer", "Casual", "Elite")))|&gt;
  rename(srt_actual_mean = simple_reaction_time_actual_mean_rt_ms,
         srt_diff_mean = simple_reaction_time_mean_rt,
         srt_practice_mean = simple_reaction_time_practice_mean_rt_ms,
         exercise_hrs = non_gamers_exercise_hours_week,
         gaming_hrs = non_gamers_gaming_hr_week,
         caffeine_intake = non_gamers_caffeine_intake_mg_d,
         sleep_hrs = non_gamers_sleep_hours_night,
         age = non_gamers_age_y)

# Cleaning data: Removing NA's and ensuring sex and dominant hand are treated as factors
non_cas_elite_2 &lt;- non_cas_elite|&gt;
  select(m_f, age, dominant_hand, caffeine_intake, sleep_hrs, exercise_hrs, gamer_group, srt_diff_mean, srt_practice_mean)|&gt;
  mutate(
    m_f = factor(m_f),
    dominant_hand = factor(dominant_hand))|&gt;
  drop_na()</code></pre>
</section>
<section id="exploratory-data-analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-1">7.3 Exploratory Data Analysis</h2>
<pre><code>#Boxplot of the actual mean simple reaction time for each level of gaming
p1 &lt;- non_cas_elite|&gt;
  drop_na(srt_diff_mean)|&gt;
  ggplot() +
  scale_fill_paletteer_d("nationalparkcolors::Acadia") +
  geom_boxplot(aes(x = srt_actual_mean,
                   y = gamer_group,
                   fill = gamer_group),
               color = "black") +
  labs(x = "Mean Actual Simple Reaction Time (ms)",
       y = "Gaming Level",
       color = "Gamer Group") +
  theme(legend.position = "none") +
  theme_bw()
  
p1</code></pre>
<p><img src="media/rId40.png" style="width:6.5in;height:3.71428in"></p>
<pre><code>#ggsave("srt_gamer_level.png", plot = p1, width = 10, height = 7)

level_table &lt;- non_cas_elite|&gt;
  drop_na(srt_diff_mean)|&gt;
df_stats(srt_actual_mean ~ gamer_group)

level_table
         response gamer_group    min     Q1 median      Q3   max     mean
1 srt_actual_mean   Non-Gamer 233.50 250.05 268.35 285.975 334.2 271.9417
2 srt_actual_mean      Casual 208.95 230.60 248.30 259.350 271.6 244.8976
3 srt_actual_mean       Elite 167.20 210.45 223.00 238.525 264.6 223.9316
        sd  n missing
1 27.84887 18       0
2 18.47549 21       0
3 24.46363 19       0</code></pre>
</section>
<section id="full-model-creation-output" class="level2">
<h2 class="anchored" data-anchor-id="full-model-creation-output">7.4 Full Model Creation &amp; Output</h2>
<pre><code>#Creation of the full model
full_model &lt;- lm(srt_diff_mean ~ m_f + age + dominant_hand + caffeine_intake + sleep_hrs + exercise_hrs + gamer_group + srt_practice_mean, data = non_cas_elite_2)


#Output of the full model
summary(full_model)

Call:
lm(formula = srt_diff_mean ~ m_f + age + dominant_hand + caffeine_intake + 
    sleep_hrs + exercise_hrs + gamer_group + srt_practice_mean, 
    data = non_cas_elite_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-44.008 -10.292  -0.581  10.341  35.951 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       164.21728   39.17597   4.192 0.000118 ***
m_fM                2.60123   12.09147   0.215 0.830578    
age                -0.52770    0.64997  -0.812 0.420872    
dominant_handR    -12.05222    7.54131  -1.598 0.116570    
caffeine_intake     0.01118    0.02527   0.442 0.660280    
sleep_hrs          -3.99565    2.65805  -1.503 0.139332    
exercise_hrs        0.47300    0.95057   0.498 0.621041    
gamer_groupCasual -14.75261   12.78218  -1.154 0.254151    
gamer_groupElite  -24.52584   13.74664  -1.784 0.080724 .  
srt_practice_mean  -0.43544    0.09643  -4.515 4.11e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.17 on 48 degrees of freedom
Multiple R-squared:  0.372, Adjusted R-squared:  0.2543 
F-statistic:  3.16 on 9 and 48 DF,  p-value: 0.004512</code></pre>
</section>
<section id="variable-selection" class="level2">
<h2 class="anchored" data-anchor-id="variable-selection">7.5 Variable Selection</h2>
<pre><code>#Automated variable selection using Adj. R^2 to find best model

models_r2 &lt;- regsubsets(srt_diff_mean ~ m_f + dominant_hand + gamer_group + age + caffeine_intake + sleep_hrs + exercise_hrs + srt_practice_mean,
        data = non_cas_elite_2,
        method = "exhaustive")

summary_r2 &lt;- summary(models_r2)

results &lt;- data.frame(summary_r2$which, adjr2 = summary_r2$adjr2)

# Rank models by Adj. R^2
ranked_models &lt;- results[order(results$adjr2, decreasing = TRUE), ]
head(ranked_models)
  X.Intercept.  m_fM dominant_handR gamer_groupCasual gamer_groupElite   age
5         TRUE FALSE           TRUE              TRUE             TRUE FALSE
6         TRUE FALSE           TRUE              TRUE             TRUE  TRUE
4         TRUE FALSE           TRUE              TRUE             TRUE FALSE
7         TRUE FALSE           TRUE              TRUE             TRUE  TRUE
8         TRUE FALSE           TRUE              TRUE             TRUE  TRUE
3         TRUE FALSE          FALSE              TRUE             TRUE FALSE
  caffeine_intake sleep_hrs exercise_hrs srt_practice_mean     adjr2
5           FALSE      TRUE        FALSE              TRUE 0.2977784
6           FALSE      TRUE        FALSE              TRUE 0.2885986
4           FALSE     FALSE        FALSE              TRUE 0.2833721
7           FALSE      TRUE         TRUE              TRUE 0.2808203
8            TRUE      TRUE         TRUE              TRUE 0.2688147
3           FALSE     FALSE        FALSE              TRUE 0.2594330</code></pre>
</section>
<section id="best-model-creation-nested-f-test-model-output" class="level2">
<h2 class="anchored" data-anchor-id="best-model-creation-nested-f-test-model-output">7.6 Best Model Creation, Nested F-test &amp; Model Output</h2>
<pre><code># Creation of reduced (best) model based on output of variable selection
best_model &lt;- lm(srt_diff_mean ~ sleep_hrs + dominant_hand + gamer_group + srt_practice_mean, data = non_cas_elite_2)

# Nested F-test testing whether the two models are significantly different
anova(best_model, full_model)
Analysis of Variance Table

Model 1: srt_diff_mean ~ sleep_hrs + dominant_hand + gamer_group + srt_practice_mean
Model 2: srt_diff_mean ~ m_f + age + dominant_hand + caffeine_intake + 
    sleep_hrs + exercise_hrs + gamer_group + srt_practice_mean
  Res.Df   RSS Df Sum of Sq     F Pr(&gt;F)
1     52 16165                          
2     48 15846  4    319.61 0.242 0.9131
# Output of the reduced (best) model - Manually input these values for Table 2
summary(best_model)

Call:
lm(formula = srt_diff_mean ~ sleep_hrs + dominant_hand + gamer_group + 
    srt_practice_mean, data = non_cas_elite_2)

Residuals:
    Min      1Q  Median      3Q     Max 
-44.584  -9.772  -0.438   9.381  35.939 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       148.15475   30.98086   4.782 1.47e-05 ***
sleep_hrs          -3.56725    2.46911  -1.445  0.15453    
dominant_handR    -11.23961    7.20737  -1.559  0.12495    
gamer_groupCasual -11.19285    6.24879  -1.791  0.07908 .  
gamer_groupElite  -20.44156    7.24364  -2.822  0.00674 ** 
srt_practice_mean  -0.42982    0.08825  -4.870 1.08e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.63 on 52 degrees of freedom
Multiple R-squared:  0.3594,    Adjusted R-squared:  0.2978 
F-statistic: 5.834 on 5 and 52 DF,  p-value: 0.000238</code></pre>
</section>
<section id="assumptionscondition-checks-for-best-model" class="level2">
<h2 class="anchored" data-anchor-id="assumptionscondition-checks-for-best-model">7.7 Assumptions/Condition Checks for Best Model</h2>
<pre><code>#Linearity check
non_cas_elite_2|&gt;
gf_point(srt_diff_mean ~ srt_practice_mean,
        shape = ~gamer_group, color = ~gamer_group,
         xlab = "Simple reaction time practice mean (ms)",
         ylab = "Difference of means simple reaction time (ms)") |&gt;
  gf_lm() +
  scale_color_viridis_d()</code></pre>
<p><img src="media/rId47.png" style="width:5.05263in;height:4.04211in"></p>
<pre><code>non_cas_elite_2|&gt;
gf_point(srt_diff_mean ~ srt_practice_mean,
        shape = ~dominant_hand, color = ~dominant_hand,
         xlab = "Simple reaction time practice mean (ms)",
         ylab = "Difference of means simple reaction time (ms)") |&gt;
  gf_lm() +
  scale_color_viridis_d()</code></pre>
<p><img src="media/rId50.png" style="width:5.05263in;height:4.04211in"></p>
<pre><code>non_cas_elite_2|&gt;
gf_point(srt_diff_mean ~ sleep_hrs,
        shape = ~dominant_hand, color = ~dominant_hand,
         xlab = "Hours of Sleep per Night",
         ylab = "Difference of means simple reaction time (ms)") |&gt;
  gf_lm() +
  scale_color_viridis_d()</code></pre>
<p><img src="media/rId53.png" style="width:5.05263in;height:4.04211in"></p>
<pre><code>non_cas_elite_2|&gt;
gf_point(srt_diff_mean ~ sleep_hrs,
        shape = ~gamer_group, color = ~gamer_group,
         xlab = "Hours of Sleep per Night",
         ylab = "Difference of means simple reaction time (ms)") |&gt;
  gf_lm() +
  scale_color_viridis_d()</code></pre>
<p><img src="media/rId56.png" style="width:5.05263in;height:4.04211in"></p>
<pre><code># Collinearity assumption check
vif(best_model)
                      GVIF Df GVIF^(1/(2*Df))
sleep_hrs         1.093217  1        1.045570
dominant_hand     1.028512  1        1.014156
gamer_group       1.608675  2        1.126204
srt_practice_mean 1.519908  1        1.232846
# Independence &amp; equal variance of residuals check
plot(best_model, 1, add.smooth = FALSE)</code></pre>
<p><img src="media/rId59.png" style="width:5.05263in;height:4.04211in"></p>
<pre><code># Normality of residuals check
plot(best_model, 2)</code></pre>
<p><img src="media/rId62.png" style="width:5.05263in;height:4.04211in"></p>
<pre><code># No influential points check
plot(best_model, 5, add.smooth = FALSE)</code></pre>
<p><img src="media/rId65.png" style="width:5.05263in;height:4.04211in"></p>
<pre><code># The residuals for the fitted values of mean simple reaction time (ms) for our model with dominant hand, mean practice simple reaction time (ms), gaming level, and hours of sleep per week (hrs) closely follows the 1:1 line, with 3 moderate deviations below the line near the lower tail, leaving no indication of systematic deviation. Given n = 58, the very slight deviation observed from the 1:1 line is acceptable. Thus, the residuals have a cumulative frequency rate that increases at the same rate of the normal curve meeting normality. The spread of the residuals about zero appears to be relatively the same across all fitted values of mean simple reaction time (ms) supporting equal variance. The distribution of the residuals about zero appears to be random across all fitted values of mean simple reaction time (ms) supporting independence. Given there are no points past Cook’s Distance of either 0.5 or 1, there are no outliers or influential points suggesting a disproportionate impact on the regression estimates. Based on the output of the VIF scores using the GVIF (adjusted) there is no presence of collinearity (VIF&lt;10). However, the intersection of our slopes within the scatterplots suggests that linearity is not met. Thus all conditions aside from linearity are met.</code></pre>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>